var world = "World";
console.log ("Hello, " + world);
world = "mon";
console.log ("Hello, " + world);
world = "mundo";
console.log ("Hello, " + world);
world = "monde";
console.log ("Hello, " + world);
world = "dunia";
console.log ("Hello, " + world);
world = "món";
console.log ("Hello, " + world);
world = "mundua";
console.log ("Hello, " + world);
world = "Terrarum";
console.log ("Hello, " + world);
world = "mhlaba";